name-template: '$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Breaking Changes'
    labels:
      - breaking
  - title: 🚀 Features
    labels:
      - feature
  - title: 🐛 Bug Fixes
    labels:
      - bug
  - title: 🔐 Security updates
    labels:
      - security
  - title: ⚠️ Maintenance
    labels:
      - maintenance
  - title: 📄 Documentation
    labels:
      - docs
  - title: 🧩 Dependency Updates
    labels:
      - deps
      - dependencies
    collapse-after: 5
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
exclude-labels:
  - 'skip-changelog'
version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - feature
      - performance
  patch:
    labels:
      - 'bug'
      - 'maintenance'
      - 'dependencies'
      - 'security'
      - 'docs'
autolabeler:
  - label: breaking
    title:
      - '/^break!:/i'
      - '/^BREAKING CHANGE:/i'
    branch:
      - '/^breaking\//'
  - label: feature
    title:
      - '/^feat:/i'
    branch:
      - '/^feature\//'
      - '/^feat\//'
  - label: bug
    title:
      - '/^fix:/i'
    branch:
      - '/^fix\//'
      - '/^bugfix\//'
      - '/^hotfix\//'
  - label: security
    title:
      - '/^security:/i'
    branch:
      - '/^security\//'
  - label: performance
    title:
      - '/^perf:/i'
    branch:
      - '/^perf\//'
  - label: maintenance
    title:
      - '/^chore:/i'
      - '/^refactor:/i'
      - '/^style:/i'
    branch:
      - '/^chore\//'
      - '/^refactor\//'
      - '/^maintenance\//'
  - label: docs
    title:
      - '/^docs:/i'
    branch:
      - '/^docs\//'
      - '/^documentation\//'
  - label: dependencies
    title:
      - '/^deps:/i'
      - '/^build:/i'
    branch:
      - '/^renovate\//'
      - '/^dependabot\//'
      - '/^deps\//'
template: |
  # What's Changed
  $CHANGES

  **Full Changelog**: <https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION>
