apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: networth-tracker-data
  labels:
    app: networth-tracker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
