apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: ghcr.io/brpaz/networth-tracker
    newTag: ${IMAGE_TAG}

resources:
  - namespace.yaml
  - service-account.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
